[versions]
junit = { strictly = '5.8.2' }
nva = {strictly = '1.30.3'}
jackson = { strictly = '2.15.2' }
mockito = { strictly = '4.5.1' }
hamcrest = { strictly = '2.2' }
zalando = { strictly = '0.27.1' }
awsLambdaJavaCore = { strictly = '1.2.2' }
awsLambdaEvents = { strictly = '3.11.2' }
log4j = { strictly = '2.17.2' }
slf4j = { strictly = '1.8.0-beta4' }
awslog4j2 = { strictly = '1.5.1' }
wiremock = { strictly = '2.33.2' }
commons-validator-version = { strictly = '1.7'}
awsSdk = { strictly = '1.12.462' }
awsSdk2 = { strictly = '2.20.60' }
jena = { strictly = '4.7.0'}

[libraries]
junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit' }
mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
nva-testutils = { group = 'com.github.bibsysdev', name = 'nvatestutils', version.ref = 'nva' }
nva-logutils = { group = 'com.github.bibsysdev', name = 'logutils', version.ref = 'nva' }
nva-json = { group = 'com.github.bibsysdev', name = 'json', version.ref = 'nva' }
nva-core = { group = 'com.github.bibsysdev', name = 'core', version.ref = 'nva' }
nva-s3 = { group = 'com.github.bibsysdev', name = 's3', version.ref = 'nva' }
zalando = { group = 'org.zalando', name = 'problem', version.ref = 'zalando' }

nva-commons-core = { group = 'com.github.bibsysdev', name = 'core', version.ref = 'nva' }
nva-commons-auth = { group = 'com.github.bibsysdev', name = 'auth', version.ref = 'nva' }
nva-commons-apigateway = { group = 'com.github.bibsysdev', name = 'apigateway', version.ref = 'nva' }
nva-commons-pagination = { group = 'com.github.bibsysdev', name = 'pagination', version.ref = 'nva'}
nva-commons-secrets = { group = 'com.github.bibsysdev', name = 'secrets', version.ref = 'nva'}
nva-eventhandlers = { group = 'com.github.bibsysdev', name = 'eventhandlers', version.ref = 'nva' }
nva-secrets = { group = 'com.github.bibsysdev', name = 'secrets', version.ref = 'nva' }

aws-sdk2-eventbridge = { group = 'software.amazon.awssdk', name = 'eventbridge', version.ref = 'awsSdk2' }
aws-sdk2-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'awsSdk2' }
aws-sdk2-sqs = { group = 'software.amazon.awssdk', name = 'sqs', version.ref = 'awsSdk2' }
aws-sdk2-core = { group = 'software.amazon.awssdk', name = 'sdk-core', version.ref = 'awsSdk2' }
aws-sdk2-urlconnection = { group = 'software.amazon.awssdk', name = 'url-connection-client', version.ref = 'awsSdk2' }
aws-sdk2-apache-client = { group = 'software.amazon.awssdk', name = 'apache-client', version.ref = 'awsSdk2' }
aws-sdk2-httpClientApi = { group = 'software.amazon.awssdk', name = 'http-client-spi', version.ref = 'awsSdk2' }
aws-sdk2-utils = { group = 'software.amazon.awssdk', name = 'utils', version.ref = 'awsSdk2' }
aws-sdk2-auth = { group = 'software.amazon.awssdk', name = 'auth', version.ref = 'awsSdk2' }
aws-sdk2-secrets = { group = 'software.amazon.awssdk', name = 'secretsmanager', version.ref = 'awsSdk2' }
aws-sdk2-regions = { group = 'software.amazon.awssdk', name = 'regions', version.ref = 'awsSdk2' }

jackson-core = { group = 'com.fasterxml.jackson.core', name = 'jackson-core', version.ref = 'jackson' }
jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }
jackson-annotations = { group = 'com.fasterxml.jackson.core', name = 'jackson-annotations', version.ref = 'jackson' }
jackson-datatype-jdk8 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jdk8', version.ref = 'jackson' }
jackson-datatype-jsr310 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jsr310', version.ref = 'jackson' }

aws-java-sdk-core = { group = 'com.amazonaws', name = 'aws-java-sdk-core', version.ref = 'awsSdk' }
aws-lambda-java-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'awsLambdaJavaCore' }
aws-lambda-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'awsLambdaEvents' }
aws-lambda-log4j2 = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'awslog4j2'}

log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4j' }
log4j-slf4j18-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j18-impl', version.ref = 'log4j' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }

wiremock = { group = 'com.github.tomakehurst', name = 'wiremock-jre8', version.ref = 'wiremock' }

commons-validator = { group = 'commons-validator', name = 'commons-validator', version.ref = 'commons-validator-version'}

jena-core = { group=  'org.apache.jena', name = 'jena-core', version.ref = 'jena' }
jena-arq = { group = 'org.apache.jena', name = 'jena-arq', version.ref = 'jena' }

[bundles]
nva = ['nva-commons-core', 'nva-commons-apigateway', 'nva-json', 'nva-commons-pagination', 'nva-commons-secrets']
logging = ['log4j-core', 'log4j-api', 'log4j-slf4j18-impl', 'slf4j-api', 'nva-logutils']
testing = ['junit-jupiter-api', 'junit-jupiter-params', 'junit-jupiter-engine', 'mockito-core', 'hamcrest', 'nva-testutils', 'nva-logutils', 'zalando', 'wiremock']
jackson = ['jackson-core', 'jackson-databind', 'jackson-annotations', 'jackson-datatype-jdk8', 'jackson-datatype-jsr310']
others = ['slf4j-api', 'log4j-api', 'aws-lambda-java-core']
jena = ['jena-core', 'jena-arq']
